name: SLK Shop
favicon: null
layout_spectrum: 0.7347033186815679
typography_spectrum: 0.7067130906507373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.19813076639547944
  lightness: 0.30015547620132565
  saturation: 0.5855773002840579
  rhythmicContrast: 0.9329154656734318
purpose: []
