name: SLK Shop
favicon: null
layout_spectrum: 0.7347033186815679
typography_spectrum: 1
title: 'Mother/Daughter Makers : Bespoke Leather Goods Made In The U.S.A.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#818286'
    - '#3a3a3c'
    - '#b8dcd2'
    - '#9c9c9c'
  brandStrength: 0.19813076639547944
  lightness: 0.30015547620132565
  saturation: 0.5855773002840579
  rhythmicContrast: 0.9329154656734318
purpose: []
